[package]
name = "spin-http-rust-example"
authors = ["Rui Lopes <rgl@ruilopes.com>"]
description = "Example Spin HTTP Application written in Rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
askama = "0.12.1"
spin-sdk = "2.2.0"

[workspace]
