[package]
name = "spin-http-rust-example"
authors = ["Rui Lopes <rgl@ruilopes.com>"]
description = "Example Spin HTTP Application written in Rust"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.83"
askama = "0.12.1"
spin-sdk = "3.0.1"

[workspace]
